import './globals.css'
import type {Metadata} from 'next'
import {Roboto} from 'next/font/google'
import {Navbar} from "@/components/navbar/navbar";

const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
    variable: '--roboto'
})


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={roboto.className}>
      <div className="flex flex-col min-h-screen">
          <Navbar></Navbar>
          {children}
      </div>
      </body>
      </html>
  )
}
